### ISSUE TITLE
npm run deploy

### ISSUE THREAD

**Issue by biofavor** [HiJesse/Demeter#2]
执行到npm run deploy
PM2显示
Name: demeter
mode: fork
status: errored

PM2 monit显示
Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    --------------------
npm start也是一样的错误，请问是有些依赖没有安装好吗？

**Comment by biofavor** [comment]
64位win7的操作系统

**Comment by HiJesse** [comment]
@biofavor  建议在release分支操作, master分支还在做重构.

**Comment by biofavor** [comment]
bundle.js:1 Uncaught SyntaxError: Unexpected token <
release版npm start报错。

**Comment by HiJesse** [comment]
@biofavor 我这的nodejs版本是v7.2.1 你用这个版本试试?

**Comment by 290352095** [comment]
npm run deploy   之后   demeter的 status 是  errored  该怎么处理一下

**Comment by HiJesse** [comment]
@290352095  node版本跟标记的一样么, 贴下日志吧

**Comment by 290352095** [comment]
![image](https://user-images.githubusercontent.com/23628090/48194413-e5c84e80-e387-11e8-9f78-2ead5c69fbc9.png)
@HiJesse

**Comment by 290352095** [comment]
![image](https://user-images.githubusercontent.com/23628090/48194464-0e504880-e388-11e8-8fc6-cc2e42dd66df.png)
@HiJesse

**Comment by HiJesse** [comment]
@290352095  看截图是启动了, 但是启动之后挂掉了. 启动demeter后会在根目录的logs目录下的文件中打印日志. 可以根据那里的错误信息排查原因.

**Comment by 290352095** [comment]
日志是空的，我看过了，有文件在，但是文件为空 @HiJesse

**Comment by HiJesse** [comment]
pm2 logs 0 看看
